version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env.example
    depends_on:
      - api
      - redis
      - db

  flower:
    image: mher/flower:2.0.1
    command: ["celery", "--broker=redis://redis:6379/1", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ytsa
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
