version: "3.9"
services:
# FastAPI app container
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./.coverage-data:/app/.coverage-data

  # Celery worker container
  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: celery -A app.tasks.celery_app worker --loglevel=info
    depends_on:
      - api
      - redis
      - db

# Flower: Celery monitoring UI
  flower:
    image: mher/flower:2.0.1
    command: ["celery", "--broker=redis://redis:6379/1", "flower", "--port=5555"]
    ports:
      - "5555:5555"
    depends_on:
      - redis

# PostgreSQL database
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ytsa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh


# Redis broker & result backend
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: